### PR TITLE
Add new CFLAGS + Some Improvements

### PR DESCRIPTION
**Pull request by RetroGamer02**
Hey I was looking for more ways to possibly speed up DOSBox.

While looking I found this vogons post
[https://www.vogons.org/viewtopic.php?p=42349#p42349](url)

So I added funroll-all-loops, param max, and fomit-frame-pointer and it does seem to provide a small just barely noticeable speed boost on O3DS.

Might be worth including even if small.

Edit: Just found this.
-fomit-frame-pointer

"Don't keep the frame pointer in a register for functions that don't need one. This avoids the instructions to save, set up and restore frame pointers; it also makes an extra register available in many functions. It also makes debugging impossible on some machines."

Maybe I should remove that one?

Edit 2: Added some small improvements taken from DOSBox-X and  DOSBox Staging.

Edit 3: Fixed dynrec for O3DS but its kinda slow.

Edit 4: Added Threading for GFXEND.

### CODE REVIEW

**Comment by MrHuu** [comment]
https://github.com/MrHuu/dosbox-3ds/blob/3DS/src/gui/sdlmain.cpp
is replaced by:
https://github.com/MrHuu/dosbox-3ds/blob/3DS/src/platform/ctr/ctr_main.cpp

I haven't restored the contents of ```sdlmain.cpp``` yet, but it's excluded when building with the current makefile.

Otherwise it's looking good, i'll have to dig up an old 3ds to checkout these changes. I'm sure this will make old3ds users very happy.

For the compilation flags, i'll have to read into those a bit more. Probably also add some debug timers to actually measure improvements or regressions.

**Comment by RetroGamer02** [comment]
> https://github.com/MrHuu/dosbox-3ds/blob/3DS/src/gui/sdlmain.cpp is replaced by: https://github.com/MrHuu/dosbox-3ds/blob/3DS/src/platform/ctr/ctr_main.cpp
> 
> I haven't restored the contents of `sdlmain.cpp` yet, but it's excluded when building with the current makefile.
> 
> Otherwise it's looking good, i'll have to dig up an old 3ds to checkout these changes. I'm sure this will make old3ds users very happy.
> 
> For the compilation flags, i'll have to read into those a bit more. Probably also add some debug timers to actually measure improvements or regressions.

Good to know I have been working on a Bitshifting Test branch that needs a lot of testing to be sure it does not break anything but brings noticeable speed improvements. Will let you know how that goes.

Edit: Added a prebuilt 3dsx file for you and anyone else that wants to try out the Bitshift Test Build.
[https://github.com/RetroGamer02/dosbox-3ds/releases/tag/v0.0.5-Test](url)

**Comment by MrHuu** [comment]
My apologies for the delay. I've been testing these changes for some time now, on a new3ds. So far everything seemingly runs ok, i do notice some regression. Mainly windows 95, which crashes dos itself. This could be caused by hardware changes which windows doesn't agree with, and can probably be resolved by reinstalling.

I did not test this on a old3ds yet. In the upcoming days, i'll try to test some more scenarios. As-well as the old3ds.

There's one minor detail, i really like all added code to be guarded by ```#ifdef __3DS__```.

After merging, i'll rebase the port on the latest svn r4483, which also solves a few loading / mounting issues for me.

**Comment by RetroGamer02** [comment]
> My apologies for the delay. I've been testing these changes for some time now, on a new3ds. So far everything seemingly runs ok, i do notice some regression. Mainly windows 95, which crashes dos itself. This could be caused by hardware changes which windows doesn't agree with, and can probably be resolved by reinstalling.
> 
> I did not test this on a old3ds yet. In the upcoming days, i'll try to test some more scenarios. As-well as the old3ds.
> 
> There's one minor detail, i really like all added code to be guarded by `#ifdef __3DS__`.
> 
> After merging, i'll rebase the port on the latest svn r4483, which also solves a few loading / mounting issues for me.

All good Ill try to add the ifdefs soon. Lookin forward to a new release.

**Comment by RetroGamer02** [comment]
Is this good?

**Comment by MrHuu** [comment]
Looks good. There's a few nits, i'll go over myself some other time.
Runs good on a new3ds. I still haven't tested on a old3ds, so we'll have to go with your results.

Thank you for these improvements, my apologies for the delays.

**Pull request merged**
