### PR TITLE
Use ARMv6 CPU Instructions

### PR DESCRIPTION
**Pull request by RetroGamer02**
Should speed up things I think. I don't have a New3DS for testing that part but I think it should work fine.
I noticed there was a number of ARMv7LE Instructions that can actually run on a 3DS ARMv6K.

### CODE REVIEW

**Comment by MrHuu** [comment]
This looks pretty good! Your interest is much appreciated.
Were you able to test it on a old3ds but any chance?

I do have a fair bit of uncommitted code locally, not yet ready to merge.
I'll make sure to check this out with the current codebase, and verify on a new3ds probably this weekend.

**Comment by RetroGamer02** [comment]
> This looks pretty good! Your interest is much appreciated. Were you able to test it on a old3ds but any chance?
> 
> I do have a fair bit of uncommitted code locally, not yet ready to merge. I'll make sure to check this out with the current codebase, and verify on a new3ds probably this weekend.

I tested what I could on Old3DS yes sorry I cant test it with New3DS myself but I just don't have the hardware.

**Comment by MrHuu** [comment]
I've tested multiple cases using the dynamic core, all seemingly without issues.
I haven't done any extensive timing measurements so i can't really tell where and if there are any performance improvements / regressions.

This is a very welcome optimization.

**Comment by RetroGamer02** [comment]
Glad to be able to help. =)

**Comment by RetroGamer02** [comment]
I know you just got around to testing it but I made some changes. Sorry about that.

**Comment by MrHuu** [comment]
Not a problem at all. Looks good! I've been going through most of the changes i've made myself and going to push them.
I'll merge this as well, feel free to open a new pr if desired. Very much appreciated.

**Pull request merged**
